name: CI

on:
  push:
    branches:
      - backup

env:
  GIT_USER: mxy
  GIT_EMAIL: mxy493@qq.com

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [ '14' ]

    steps:
      - name: Checkout backup branch
        uses: actions/checkout@v3
        with:
          ref: backup

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: .deploy_git

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Install dependencies
        run: |
          npm install

      - name: Deploy hexo
        run: |
          npm run deploy
